import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'
import type { ClientBindingsDocument } from './types.ts'

const DEFAULT_BINDINGS_BANNER = `// This file is auto-generated by @edaya/client-codegen
// Do not edit manually.
`

export function formatClientBindingsTypeScript(
	clientBindings: ClientBindingsDocument,
	options: { banner?: string } = {},
): string {
	const banner = options.banner ?? DEFAULT_BINDINGS_BANNER
	const formatted = JSON.stringify(clientBindings, null, 2)
		.split('\n')
		.map((line, index) => (index === 0 ? line : `  ${line}`))
		.join('\n')

	return `${banner}
export const clientBindings = ${formatted} as const

export type ClientBindings = typeof clientBindings
`
}

export function writeClientBindingsTypeScript(
	clientBindings: ClientBindingsDocument,
	outputPath: string,
	options: { banner?: string } = {},
): void {
	mkdirSync(dirname(outputPath), { recursive: true })
	writeFileSync(outputPath, formatClientBindingsTypeScript(clientBindings, options))
}
