export const DEFAULT_BINDINGS_BANNER = `// This file is auto-generated by @edaya/client-codegen
// Do not edit manually.
`

export const DEFAULT_CLIENT_BANNER = `// This file is auto-generated by @edaya/client-codegen
// Do not edit manually.
`
